"""
Response Analysis Engine
========================
Differentiates a genuine AEM 404 from a Dispatcher/WAF-generated 404 or 403.
Extracts tier-identification signals from response headers and body markers
so subsequent checks can decide whether to pursue bypass variants.
"""
from __future__ import annotations

import re
from dataclasses import dataclass, field
from typing import Dict, List, Optional

from .models import HttpResult

# ---------------------------------------------------------------------------
# Tier markers
# ---------------------------------------------------------------------------

# Keywords in the response body that strongly indicate the response was
# generated by the AEM Sling/CQ layer (not a frontend proxy).
_AEM_BODY_MARKERS: List[str] = [
    "sling:",
    "jcr:",
    "cq:",
    "com.day.cq",
    "granite",
    "/libs/",
    "Felix",
    "Apache Sling",
    "Adobe Experience Manager",
    "CRX",
    "Jackrabbit",
    "rep:policy",
]

# Response headers whose presence usually indicates an AEM Publisher/Author
# actually served the response.
_AEM_HEADER_KEYS: List[str] = [
    "x-aem-version",
    "x-granite-",
    "x-content-granularity",
    "x-cq-",
    "x-sling-",
]

# Response headers whose presence suggests a Dispatcher, CDN, or WAF
# intercepted the request before it reached the AEM tier.
_EDGE_HEADER_KEYS: List[str] = [
    "x-dispatcher",
    "x-vhost",
    "via",
    "x-cache",
    "x-cdn",
    "cf-ray",           # Cloudflare
    "x-amz-cf-id",      # CloudFront
    "x-akamai-",        # Akamai
    "x-sucuri-id",      # Sucuri WAF
    "x-waf-",
    "x-forwarded-",
    "x-azure-ref",      # Azure Front Door
    "x-cnection",       # BIG-IP
    "x-wa-info",        # BIG-IP WebAccelerator
    "x-f5-",            # BIG-IP family
    "x-envoy-",         # Envoy-based gateways
    "x-iinfo",          # Imperva
]

# Generic web-server 404 body patterns (no AEM-specific content).
_GENERIC_BODY_PATTERNS: List[str] = [
    "404 not found",
    "403 forbidden",
    "access denied",
    "page not found",
    "object not found",
    "the requested url",
    "nginx",
    "apache/",
]

# Distinguishable AEM 404 body patterns.
_AEM_404_BODY_PATTERNS: List[str] = [
    "404 Resource type not found",
    "The specified resource does not exist",
    "org.apache.sling.api.resource.ResourceNotFoundException",
    "SlingException",
    "NoSuchResourceException",
]

_WAF_BLOCK_BODY_PATTERNS: List[str] = [
    "the requested url was rejected",
    "request rejected",
    "asm support id",
    "access denied",
    "web application firewall",
    "incident id",
]


# ---------------------------------------------------------------------------
# Result dataclass
# ---------------------------------------------------------------------------

@dataclass
class ResponseTierAnalysis:
    """Result produced by `analyse_response`."""

    # High-level classification
    tier: str                           # "aem", "dispatcher", "cdn", "unknown"
    is_true_aem_response: bool          # Response definitively from the AEM JVM
    is_edge_blocked: bool               # Filtered at Dispatcher / WAF / CDN

    # HTTP surface details
    status_code: Optional[int]
    effective_url: str

    # Header signals
    aem_headers_found: List[str]        # AEM-specific headers detected
    edge_headers_found: List[str]       # Edge/proxy headers detected
    server_banner: Optional[str]        # Value of the "Server" header if present
    via_chain: Optional[str]            # Value of the "Via" header if present
    x_vhost: Optional[str]
    dispatcher_present: bool            # Explicit dispatcher header

    # Body signals
    aem_body_markers_found: List[str]
    is_aem_404: bool                    # AEM generated the 404 itself
    is_generic_404: bool                # Frontend generated the 404

    # Confidence 0-100
    aem_confidence: int
    edge_confidence: int

    # Human-readable rationale
    rationale: str
    recommendations: List[str] = field(default_factory=list)


def analyse_response(result: HttpResult) -> ResponseTierAnalysis:
    """
    Analyse a single HTTP result to determine whether the response came from
    the AEM tier or was intercepted by a Dispatcher/WAF/CDN.

    Parameters
    ----------
    result : HttpResult
        The raw HTTP result from the client.

    Returns
    -------
    ResponseTierAnalysis
        Structured analysis with tier classification and confidence scores.
    """
    headers_lower: Dict[str, str] = {k.lower(): v for k, v in result.headers.items()}
    body_lower: str = (result.text or "").lower()

    # ------------------------------------------------------------------
    # Header checks
    # ------------------------------------------------------------------
    aem_headers_found: List[str] = []
    for key_prefix in _AEM_HEADER_KEYS:
        for hk in headers_lower:
            if hk.startswith(key_prefix.lower()) and hk not in aem_headers_found:
                aem_headers_found.append(hk)

    edge_headers_found: List[str] = []
    for key_prefix in _EDGE_HEADER_KEYS:
        for hk in headers_lower:
            if hk.startswith(key_prefix.lower()) and hk not in edge_headers_found:
                edge_headers_found.append(hk)

    server_banner = headers_lower.get("server")
    via_chain = headers_lower.get("via")
    x_vhost = headers_lower.get("x-vhost")
    dispatcher_present = "x-dispatcher" in headers_lower or (
        server_banner and "dispatcher" in server_banner.lower()
    )

    # ------------------------------------------------------------------
    # Body checks
    # ------------------------------------------------------------------
    aem_body_markers_found = [
        m for m in _AEM_BODY_MARKERS if m.lower() in body_lower
    ]

    is_aem_404 = any(p.lower() in body_lower for p in _AEM_404_BODY_PATTERNS)
    is_generic_404 = any(p.lower() in body_lower for p in _GENERIC_BODY_PATTERNS)
    waf_block_page = any(p in body_lower for p in _WAF_BLOCK_BODY_PATTERNS)

    # ------------------------------------------------------------------
    # Confidence scoring (0-100)
    # ------------------------------------------------------------------
    aem_confidence = 0
    edge_confidence = 0

    aem_confidence += min(len(aem_body_markers_found) * 15, 40)
    aem_confidence += min(len(aem_headers_found) * 20, 40)
    if is_aem_404:
        aem_confidence += 25
    # 401/403 from Sling looks like AEM
    if result.status_code in (401, 403) and aem_body_markers_found:
        aem_confidence += 10

    edge_confidence += 20 if dispatcher_present else 0
    edge_confidence += 15 if via_chain else 0
    edge_confidence += 10 if x_vhost else 0
    edge_confidence += min(len(edge_headers_found) * 10, 30)
    if is_generic_404 and not aem_body_markers_found:
        edge_confidence += 20
    if server_banner and re.search(r"nginx|apache(?!/sling)|iis|lighttpd|varnish", server_banner, re.I):
        edge_confidence += 15
    if waf_block_page:
        edge_confidence += 20
    if "set-cookie" in headers_lower and any(
        cookie_hint in headers_lower.get("set-cookie", "").lower()
        for cookie_hint in ("bigipserver", "f5avr", "ts01", "ts0")
    ):
        edge_confidence += 15

    aem_confidence = min(aem_confidence, 100)
    edge_confidence = min(edge_confidence, 100)

    # ------------------------------------------------------------------
    # Tier classification
    # ------------------------------------------------------------------
    is_true_aem_response = aem_confidence >= 50 and aem_confidence > edge_confidence
    is_edge_blocked = edge_confidence >= 50 and edge_confidence > aem_confidence

    if is_true_aem_response:
        tier = "aem"
    elif is_edge_blocked:
        if dispatcher_present:
            tier = "dispatcher"
        elif via_chain or any("cf-ray" in h or "x-amz" in h for h in edge_headers_found):
            tier = "cdn"
        else:
            tier = "edge"
    else:
        tier = "unknown"

    # ------------------------------------------------------------------
    # Rationale
    # ------------------------------------------------------------------
    rationale_parts = []
    if aem_body_markers_found:
        rationale_parts.append(f"AEM body markers: {aem_body_markers_found[:3]}")
    if aem_headers_found:
        rationale_parts.append(f"AEM headers: {aem_headers_found[:3]}")
    if edge_headers_found:
        rationale_parts.append(f"Edge headers: {edge_headers_found[:3]}")
    if via_chain:
        rationale_parts.append(f"Via: {via_chain[:80]}")
    if server_banner:
        rationale_parts.append(f"Server: {server_banner}")
    if not rationale_parts:
        rationale_parts.append("No distinguishing markers found; tier classification uncertain.")

    rationale = f"tier={tier}. " + " | ".join(rationale_parts)

    # ------------------------------------------------------------------
    # Recommendations
    # ------------------------------------------------------------------
    recommendations: List[str] = []
    if is_edge_blocked:
        recommendations.append(
            "Response was filtered before reaching AEM. "
            "Try dispatcher bypass variants (semicolon, double-slash, encoded chars) "
            "or route directly to the publish/author port if accessible."
        )
    if via_chain:
        recommendations.append(
            f"Via header present ({via_chain[:60]}). Consider direct-IP probing to bypass the CDN layer."
        )
    if dispatcher_present:
        recommendations.append(
            "Dispatcher header detected. Test path normalization bypasses: ..;/, //, %2f, %252f."
        )
    if is_true_aem_response and result.status_code in (401, 403):
        recommendations.append(
            "Request reached AEM but was denied at the ACL layer. "
            "Try credentials or selector-based information disclosure."
        )

    return ResponseTierAnalysis(
        tier=tier,
        is_true_aem_response=is_true_aem_response,
        is_edge_blocked=is_edge_blocked,
        status_code=result.status_code,
        effective_url=result.url,
        aem_headers_found=aem_headers_found,
        edge_headers_found=edge_headers_found,
        server_banner=server_banner,
        via_chain=via_chain,
        x_vhost=x_vhost,
        dispatcher_present=dispatcher_present,
        aem_body_markers_found=aem_body_markers_found[:5],
        is_aem_404=is_aem_404,
        is_generic_404=is_generic_404,
        aem_confidence=aem_confidence,
        edge_confidence=edge_confidence,
        rationale=rationale,
        recommendations=recommendations,
    )


def tier_finding_rationale(analysis: ResponseTierAnalysis) -> str:
    """
    Return a compact one-liner suitable for embedding in a Finding rationale.
    """
    return (
        f"[TierAnalysis] tier={analysis.tier}. "
        f"{analysis.rationale[:220]}"
    )
